// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChsgqhAYozQpuSdYsv0j2Dg14Z9j0EufU',
    appId: '1:380268421012:web:a552a58284a9b7d90eb981',
    messagingSenderId: '380268421012',
    projectId: 'fitlife-1ceb3',
    authDomain: 'fitlife-1ceb3.firebaseapp.com',
    storageBucket: 'fitlife-1ceb3.appspot.com',
    measurementId: 'G-74REJGBSSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPOx_jm8F6F6nTVJ4KuwFFvC4hlMnLBU',
    appId: '1:380268421012:android:b5726fbe741976990eb981',
    messagingSenderId: '380268421012',
    projectId: 'fitlife-1ceb3',
    storageBucket: 'fitlife-1ceb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42KlfyvXHgA7lNChSDQLCjUp7toWwhPg',
    appId: '1:380268421012:ios:d1af85eb61f8e6870eb981',
    messagingSenderId: '380268421012',
    projectId: 'fitlife-1ceb3',
    storageBucket: 'fitlife-1ceb3.appspot.com',
    iosBundleId: 'com.example.gamestellar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42KlfyvXHgA7lNChSDQLCjUp7toWwhPg',
    appId: '1:380268421012:ios:58ab8f0f06b32e020eb981',
    messagingSenderId: '380268421012',
    projectId: 'fitlife-1ceb3',
    storageBucket: 'fitlife-1ceb3.appspot.com',
    iosBundleId: 'com.example.gamestellar.RunnerTests',
  );
}
